package Interfaces;

import Clases.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Albany Avila
 */
public class ManejoDocumentos extends javax.swing.JFrame {

    private HashTable tabla;
    private Top5 top5;
    private Archivero rabinkarp;

    public ManejoDocumentos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.tabla = new HashTable(10111);
        this.top5 = new Top5();
        this.rabinkarp = new Archivero();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        cargarArchivo = new javax.swing.JButton();
        elegirDocumento = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        verificar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarArchivo.setBackground(new java.awt.Color(190, 144, 130));
        cargarArchivo.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        cargarArchivo.setText("Cargar Archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        panel1.add(cargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 190, -1));

        elegirDocumento.setBackground(new java.awt.Color(190, 144, 130));
        elegirDocumento.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        elegirDocumento.setText("Elegir Documento");
        elegirDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirDocumentoActionPerformed(evt);
            }
        });
        panel1.add(elegirDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 190, -1));

        cerrar.setBackground(new java.awt.Color(190, 144, 130));
        cerrar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        panel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, -1, -1));

        jTextField1.setBackground(new java.awt.Color(242, 227, 221));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 290, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Top 5 de palabras:");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jTextField2.setBackground(new java.awt.Color(242, 227, 221));
        panel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, 40));

        buscar.setBackground(new java.awt.Color(190, 144, 130));
        buscar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        panel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buscar palabras:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(242, 227, 221));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 230, 230));

        verificar.setBackground(new java.awt.Color(190, 144, 130));
        verificar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        verificar.setText("Verificar Artículos");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });
        panel1.add(verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        jTextArea2.setBackground(new java.awt.Color(242, 227, 221));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        panel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 230, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/62c385f969858f518ee26296d0c7ea8d.jpg"))); // NOI18N
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 580));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed

        JOptionPane.showMessageDialog(null, "Por favor escoja el archivo que desea cargar al sistema.", "Cargar archivo", JOptionPane.INFORMATION_MESSAGE);

        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.TXT", "txt");
        fc.setFileFilter(filter);
        int select = fc.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            this.jTextField1.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void elegirDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirDocumentoActionPerformed
        String pathToFile = this.jTextField1.getText();
        if (pathToFile.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar el recuadro "
                    + "con la ruta o buscar un archivo");
        } else {
            LeerDocumento f = new LeerDocumento();
            try {
                Tabla tl = f.openFile(pathToFile, this.tabla, rabinkarp, top5);
                this.setTabla(tl.getTable());
                this.setTop5(tl.getTop5());
                this.setRabinKarp(tl.getKarpList());
                this.jTextArea1.setText(this.tabla.mostrar());
                this.jTextArea2.setText(this.top5.mostrar());
                this.jTextField1.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "El archivo cargado no "
                        + "pudo ser procesado por la plataforma. Por favor "
                        + "intente con otro archivo");
            }
        }
    }//GEN-LAST:event_elegirDocumentoActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.setVisible(false); //Se cierra la ventana
    }//GEN-LAST:event_cerrarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String buscador = this.jTextField2.getText();
        if (buscador.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese la "
                    + "palabra que desea buscar: ");
        } else {
            NodoHash resultado = this.tabla.buscarPalabra(buscador);
            if (resultado == null) {
                JOptionPane.showMessageDialog(rootPane, "No se encontró "
                        + "la palabra ingresada.");
            } else {
                if (resultado.getContarPalabras() == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Se encontró '"
                            + resultado.getPalabra() + "' 1 vez.");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Se encontró '"
                            + resultado.getPalabra() + "' "
                            + resultado.getContarPalabras() + " veces.");
                }
            }
        }

    }

    public HashTable getTabla() {
        return tabla;
    }

    public void setTabla(HashTable tabla) {
        this.tabla = tabla;
    }

    public Top5 getTop5() {
        return top5;
    }

    public void setTop5(Top5 top5) {
        this.top5 = top5;
    }

    public Archivero getRabinKarp() {
        return rabinkarp;
    }

    public void setRabinKarp(Archivero rabinkarp) {
        this.rabinkarp = rabinkarp;

    }//GEN-LAST:event_buscarActionPerformed

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        if (this.rabinkarp.tamano == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe de cargar al menos "
                    + "un artículo para poder verificar si hay plagio.");
        } else {
            Resultados karp = new Resultados();
            karp.setLocationRelativeTo(null);
            karp.setVisible(true);
        }
    }//GEN-LAST:event_verificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton elegirDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Panel panel1;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
