package Interfaces;

import Clases.ProyectoHash;
import javax.swing.JOptionPane;

/**
 *
 * @author Albany Avila
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entrar = new javax.swing.JButton();
        informacion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel3.setBackground(new java.awt.Color(190, 144, 130));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Verificador de Artículos");
        panel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 410, 60));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Verdana", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Verificador de Artículos");
        panel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 420, 70));

        panel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 140));

        entrar.setBackground(new java.awt.Color(190, 144, 130));
        entrar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        entrar.setText("Comenzar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        panel1.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 210, 40));

        informacion.setBackground(new java.awt.Color(190, 144, 130));
        informacion.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        informacion.setText("Información");
        informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacionActionPerformed(evt);
            }
        });
        panel1.add(informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 210, 40));

        salir.setBackground(new java.awt.Color(190, 144, 130));
        salir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        panel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 80, -1));

        jLabel8.setBackground(new java.awt.Color(190, 144, 130));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/62c385f969858f518ee26296d0c7ea8d.jpg"))); // NOI18N
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 560));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacionActionPerformed
        //Se muestra informacion sobre el proyecto
        JOptionPane.showMessageDialog(null, "¡Bienvenido! \nCon este programa puedes buscar palabras claves, \ncomparar y verificar si varios artículos o documentos contienen plagio.", "Bienvenida", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_informacionActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        ProyectoHash.main.setVisible(true); //Se muestra el main
        this.setVisible(false);
    }//GEN-LAST:event_entrarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0); //Al hacer click en este boton, se sale del sistema
    }//GEN-LAST:event_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JButton informacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
