package Interfaces;

import Clases.AlgoritmoRabinKarp;
import Interfaces.ManejoDocumentos;
import javax.swing.JOptionPane;


/**
 *
 * @author Albany Avila
 */
public class Resultados extends javax.swing.JFrame {

    /*
    Esta ventana solo nos servira por razones de estetica
    para mostrar los resultados del analisis del documento/
    Los datos del analisis no seran setteados en el jTextArea en esta clase sino en otra
     */
    private ManejoDocumentos manejoDocumentos;

    public Resultados() {
        
        this.manejoDocumentos = null;
        initComponents();
    }

    public Resultados(ManejoDocumentos manejoDocumentos) {
        this.manejoDocumentos = manejoDocumentos;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.jList1.setListData(this.manejoDocumentos.getRabinKarp().titulos().split(","));
        this.jList2.setListData(this.manejoDocumentos.getRabinKarp().titulos().split(","));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        cerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        verificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setBackground(new java.awt.Color(190, 144, 130));
        cerrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        panel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, -1, 30));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 200, 150));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        panel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 200, 150));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        panel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 360, 170));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione un documento:");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione un documento:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        verificar.setBackground(new java.awt.Color(190, 144, 130));
        verificar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        verificar.setText("Verificar Artículo");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });
        panel1.add(verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/62c385f969858f518ee26296d0c7ea8d.jpg"))); // NOI18N
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 530));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.setVisible(false); //Boton para cerrar la ventana
    }//GEN-LAST:event_cerrarActionPerformed

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        try {
            if (this.jTextArea3.getText().length() > 0) {
                this.jTextArea3.setText("");
            }
            String titulo = this.jList2.getSelectedValue();
            String tituloSegmento = this.jList1.getSelectedValue();
            String texto = this.manejoDocumentos.getRabinKarp().buscar(titulo).texto;
            String segmento = this.manejoDocumentos.getRabinKarp().buscar(tituloSegmento).texto;
            if (texto != null && segmento != null) {
                if (texto.length() < segmento.length()) {
                    JOptionPane.showMessageDialog(rootPane, "El documento "
                            + "seleccionado es de menor longitud. "
                            + "No se puede verificar el texto y "
                            + "buscar si existe plagio");
                } else {
                    AlgoritmoRabinKarp a = new AlgoritmoRabinKarp();
                    String resultado = a.algoritmoRabinKarp(texto, segmento);
                    this.jTextArea3.setText(resultado);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar el documento "
                    + "y el texto que desea verificar");
        }
    }//GEN-LAST:event_verificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea3;
    private java.awt.Panel panel1;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
